export const rechartsData = [
  {
    month: 'January',
    abb: 'Jan',
    name: 'Jan',
    fill: '#7a1e3f',
    users: 150,
    sessions: 280,
    bounceRate: 20,
    avgDuration: 55,
  },
  {
    month: 'February',
    abb: 'Feb',
    name: 'Feb',
    fill: '#4c8f0d',
    users: 180,
    sessions: 400,
    bounceRate: 15,
    avgDuration: 70,
  },
  {
    month: 'March',
    abb: 'Mar',
    name: 'Mar',
    fill: '#3b62a5',
    users: 220,
    sessions: 350,
    bounceRate: 25,
    avgDuration: 50,
  },
  {
    month: 'April',
    abb: 'Apr',
    name: 'Apr',
    fill: '#b58621',
    users: 270,
    sessions: 500,
    bounceRate: 10,
    avgDuration: 80,
  },
  {
    month: 'May',
    abb: 'May',
    name: 'May',
    fill: '#912e6d',
    users: 320,
    sessions: 450,
    bounceRate: 18,
    avgDuration: 65,
  },
  {
    month: 'June',
    abb: 'Jun',
    name: 'Jun',
    fill: '#2a7c8b',
    users: 400,
    sessions: 600,
    bounceRate: 12,
    avgDuration: 75,
  },
  {
    month: 'July',
    abb: 'Jul',
    name: 'Jul',
    fill: '#a53f77',
    users: 350,
    sessions: 700,
    bounceRate: 28,
    avgDuration: 45,
  },
  {
    month: 'August',
    abb: 'Aug',
    name: 'Aug',
    fill: '#5e9a34',
    users: 250,
    sessions: 550,
    bounceRate: 30,
    avgDuration: 40,
  },
  {
    month: 'September',
    abb: 'Sep',
    name: 'Sep',
    fill: '#4364b1',
    users: 300,
    sessions: 650,
    bounceRate: 5,
    avgDuration: 90,
  },
  {
    month: 'October',
    abb: 'Oct',
    name: 'Oct',
    fill: '#d1a140',
    users: 420,
    sessions: 800,
    bounceRate: 8,
    avgDuration: 85,
  },
  {
    month: 'November',
    abb: 'Nov',
    name: 'Nov',
    fill: '#a42b5b',
    users: 200,
    sessions: 750,
    bounceRate: 22,
    avgDuration: 60,
  },
  {
    month: 'December',
    abb: 'Dec',
    name: 'Dec',
    fill: '#357996',
    users: 350,
    sessions: 300,
    bounceRate: 3,
    avgDuration: 95,
  },
];

export const rechartsChartType = {
  Line: 'Line',
  Area: 'Area',
  Bar: 'Bar',
  Composed: 'Composed',
  Pie: 'Pie',
  Radar: 'Radar',
  RadialBar: 'RadialBar',
  Dashboard: 'Dashboard',
  About: 'About',
};

export const rechartsDashboardData = [
  {
    month: 'January',
    abb: 'Jan',
    users: 150,
    sessions: 280,
  },
  {
    month: 'February',
    abb: 'Feb',
    users: 180,
    sessions: 400,
  },
  {
    month: 'March',
    abb: 'Mar',
    users: 220,
    sessions: 350,
  },
  {
    month: 'April',
    abb: 'Apr',
    users: 270,
    sessions: 500,
  },
  {
    month: 'May',
    abb: 'May',
    users: 320,
    sessions: 450,
  },
  {
    month: 'June',
    abb: 'Jun',
    users: 400,
    sessions: 600,
  },
  {
    month: 'July',
    abb: 'Jul',
    users: 350,
    sessions: 700,
  },
  {
    month: 'August',
    abb: 'Aug',
    users: 250,
    sessions: 550,
  },
  {
    month: 'September',
    abb: 'Sep',
    users: 300,
    sessions: 650,
  },
  {
    month: 'October',
    abb: 'Oct',
    users: 420,
    sessions: 800,
  },
  {
    month: 'November',
    abb: 'Nov',
    users: 200,
    sessions: 750,
  },
  {
    month: 'December',
    abb: 'Dec',
    users: 350,
    sessions: 300,
  },
];

export const radialBarData = [
  {
    name: 'Home Page',
    users: 37,
    fill: '#8884d8',
  },
  {
    name: 'Contacts Page',
    users: 75,
    fill: '#27685F',
  },
];
